# Generated by Django 3.0.3 on 2021-06-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
